name: Spellcheck

on: 
  [push, pull_request]

permissions:
  contents: read

jobs:
  Spellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - run: |
        wget --no-check-certificate https://raw.githubusercontent.com/Open-Systems-Pharmacology/docs/master/.github/workflows/wordlist.txt
        mv ./wordlist.txt ./wordlist_osp_docs.txt
        ls -l ./
        cat ./.spellcheck.yml
        cat .github/workflows/SpellChecker.yml
        ls -l .github/workflows/
        cat .github/workflows/wordlist.txt
    - uses: rojopolis/spellcheck-github-actions@0.16.0
